lobby: "10 Man Lobby"
team_a: "Team A"
team_b: "Team B"
scheme:
  - "A1"
  - "B2"
  - "A1"
  - "B1"
  - "A1"
  - "B1"
  - "A1"
maps:
  - "Ascent"
  - "Fracture"
  - "Haven"
  - "Icebox"
  - "Pearl"
  - "Split"
